/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "primary-container": "#ff571a",
          "surface-container-lowest": "#190a06",
          "tertiary": "#c2c7cd",
          "outline-variant": "#5c4037",
          "on-tertiary-fixed": "#171c21",
          "surface-container-low": "#281712",
          "on-secondary": "#2f3035",
          "on-tertiary": "#2b3136",
          "on-surface": "#fcdcd3",
          "primary-fixed-dim": "#ffb59e",
          "on-secondary-fixed": "#1a1c20",
          "error": "#ffb4ab",
          "surface-container": "#2d1b16",
          "tertiary-container": "#8c9197",
          "on-secondary-container": "#b7b8be",
          "primary-fixed": "#ffdbd0",
          "secondary": "#c6c6cc",
          "on-surface-variant": "#e6beb2",
          "surface-dim": "#1f0f0b",
          "on-error-container": "#ffdad6",
          "surface-container-high": "#382620",
          "on-secondary-fixed-variant": "#45474b",
          "primary": "#ffb59e",
          "secondary-fixed": "#e2e2e8",
          "error-container": "#93000a",
          "on-primary-container": "#521300",
          "secondary-container": "#47494e",
          "inverse-primary": "#ae3200",
          "tertiary-fixed": "#dee3e9",
          "surface-tint": "#ffb59e",
          "surface-container-highest": "#44302a",
          "surface-bright": "#49342e",
          "inverse-on-surface": "#3f2c26",
          "background": "#1f0f0b",
          "on-primary": "#5e1700",
          "on-tertiary-container": "#252a2f",
          "on-error": "#690005",
          "on-background": "#fcdcd3",
          "surface": "#1f0f0b",
          "inverse-surface": "#fcdcd3",
          "on-primary-fixed-variant": "#852400",
          "tertiary-fixed-dim": "#c2c7cd",
          "on-tertiary-fixed-variant": "#42474c",
          "surface-variant": "#44302a",
          "on-primary-fixed": "#3a0b00",
          "outline": "#ad897e",
          "secondary-fixed-dim": "#c6c6cc"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "md": "24px",
          "xs": "8px",
          "container-max": "1280px",
          "lg": "48px",
          "sm": "16px",
          "base": "4px",
          "gutter": "24px",
          "xl": "80px"
      },
      "fontFamily": {
          "label-caps": ["JetBrains Mono"],
          "body-md": ["Hanken Grotesk"],
          "body-lg": ["Hanken Grotesk"],
          "headline-lg-mobile": ["Anybody"],
          "display-xl": ["Anybody"],
          "headline-lg": ["Anybody"],
          "headline-md": ["Anybody"]
      },
      "fontSize": {
          "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600" }],
          "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
          "display-xl": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
          "headline-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
